language: c++

matrix:
  include:
    - os: windows
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Visual Studio 15 2017"
        - cd ..
        - ./build.bat

    - os: linux
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Unix Makefiles"
        - make
        
