language: cpp

matrix:
  include:
    - import: 
      source: ./.travis/windowsscript.yml
    - os: windows
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Visual Studio 15 2017 Win64"
        - cd ..
        - ./build.bat Debug x64
    - os: windows        
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Visual Studio 15 2017"
        - cd ..
        - ./build.bat Release Win32        
    - os: windows        
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Visual Studio 15 2017 Win64"
        - cd ..
        - ./build.bat Release x64
    - os: linux
      dist: xenial
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Unix Makefiles"
        - make        
