language: cpp

matrix:
  include:
    - os: windows
      script:
        - import ./.travis/windowsscript.yml
        - ./build.bat Debug
    - os: windows        
      script:
        - import ./.travis/windowsscript.yml
        - ./build.bat Release        

    - os: linux
      dist: xenial
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Unix Makefiles"
        - make
      
        
