language: cpp

matrix:
  include:
    - os: windows
      script:
        import: 
          - source: ./.travis/windowsscript.yml
        - ./build.bat Debug Win32
    - os: windows
      script:
        import:
          - ./.travis/windowsscript.yml
        - ./build.bat Debug Win64
    - os: windows        
      script:
        import:
          - ./.travis/windowsscript.yml
        - ./build.bat Release Win32        
    - os: windows        
      script:
        import:
          - ./.travis/windowsscript.yml
        - ./build.bat Release Win64
    - os: linux
      dist: xenial
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Unix Makefiles"
        - make
      
        
