os: windows
language: c++
script: 
 - mkdir build
 - cd build
 - cmake .. -G"Visual Studio 15 2017"
 - "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe" build/YAML_CPP.sln
